-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 사용자 계정 테이블
-- ───────────────────────────────────────
drop table if exists user_account cascade;
create table user_account (
                              id          bigint generated by default as identity,
                              username    varchar(50) not null unique,
                              password    varchar(100) not null,
                              role        varchar(20)  not null,
                              created_at  timestamp    default current_timestamp,
                              primary key(id)
);

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 게시글 테이블
-- ───────────────────────────────────────
drop table if exists post cascade;
create table post (
                      id          bigint generated by default as identity,
                      user_id     bigint not null,
                      title       varchar(200) not null,
                      content     text,
                      created_at  timestamp     default current_timestamp,
                      primary key(id),
                      foreign key (user_id) references user_account(id)
);

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 댓글 테이블
-- ───────────────────────────────────────
drop table if exists comment cascade;
create table comment (
                         id          bigint generated by default as identity,
                         post_id     bigint not null,
                         user_id     bigint not null,
                         content     text       not null,
                         created_at  timestamp  default current_timestamp,
                         primary key(id),
                         foreign key (post_id) references post(id),
                         foreign key (user_id) references user_account(id)
);

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 좋아요 테이블
-- ───────────────────────────────────────
drop table if exists post_like cascade;
create table post_like (
                           id          bigint generated by default as identity,
                           post_id     bigint not null,
                           user_id     bigint not null,
                           created_at  timestamp  default current_timestamp,
                           primary key(id),
                           unique(post_id, user_id),
                           foreign key (post_id) references post(id),
                           foreign key (user_id) references user_account(id)
);

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 공유 테이블
-- ───────────────────────────────────────
drop table if exists share cascade;
create table share (
                       id          bigint generated by default as identity,
                       post_id     bigint not null,
                       user_id     bigint not null,
                       platform    varchar(50),
                       created_at  timestamp default current_timestamp,
                       primary key(id),
                       foreign key (post_id) references post(id),
                       foreign key (user_id) references user_account(id)
);
